module: Tabman
author: UI At Six
author_url: https://github.com/uias
github_url: https://github.com/uias/Tabman

copyright: '© 2018 [Bust Out Solutions](http://bustoutsolutions.com) under [open source license](https://github.com/bustoutsolutions/siesta/blob/master/LICENSE).'

swift_version: 4.2

theme: fullwidth